### ISSUE TITLE
API for product details using slug

### ISSUE THREAD

**Issue by thihathit** [paingpyi/efi-backend-server#2]
currently we only have list API, which is also filterable, I can just use this one.

Just one problem. It can't be filtered using either `slug` or `slug_url` in payload. Here's current listing api call, it should returns only one item if found.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/30023628/162547594-d2713f70-447f-449b-b7f9-836654334b3b.png">

I would prefer separate API though. But only if that doesn't make extra work for you. So that I can use `4xx` response when there's no data. better for my Nextjs's static optimizations.

Example: `POST /api/products/detail`

**Comment by KonjiKonoha** [comment]
This is solved. Please check the API.

**Comment by thihathit** [comment]
This works! But I think we should split listing and details to separate endpoints later, so that Nextjs's static page generation can display 404 page when api returns `404` for requested slug.

**Comment by thihathit** [comment]
for now, I'll close it. let's open new issue after we demo to client.
