### ISSUE TITLE
Blogs: `category` field data isn't correct. must be matched with `/api/blogs/categories`

### ISSUE THREAD

**Issue by thihathit** [paingpyi/efi-backend-server#22]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/30023628/164915260-32a21f2a-5b3d-43d3-9762-056a2b91dbaa.png">

Should be one/all of the following:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/30023628/164915294-873ed2f6-223d-40d0-925a-f21236c27875.png">

**Comment by thihathit** [comment]
both `id` & `name` must be matched

**Comment by thihathit** [comment]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/30023628/164968616-a10e2b8a-e90e-4153-98b1-ddf72a4d0172.png">

and

<img width="969" alt="image" src="https://user-images.githubusercontent.com/30023628/164968582-7e2f0e21-d961-4426-b510-1aa2831496a6.png">

**Comment by KonjiKonoha** [comment]
I need the Blog's categories from client, bro.

**Comment by thihathit** [comment]
no need for real data bro. the problem here is about not having relationships between `category's id` onto `blog's category field`. As well as `name`

**Comment by KonjiKonoha** [comment]
This is because of I copied the category. In the database, duplicated categories have been stored.

**Comment by thihathit** [comment]
i don't know how it's stored, they're supposed to be referenced each other. but If they're not the same, can't be filtered.

🎥 https://temp.sh/ZgFLg/Screen%20Recording%202022-04-25%20at%201.51.25%20AM.mov

Currently the list is returning all the 25 nodes, the filtering doesn't work anymore.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/30023628/164991957-a5c037f9-7926-4dfe-a5b2-cbca2898b063.png">
