### ISSUE TITLE
One page APIs

### ISSUE THREAD

**Issue by thihathit** [paingpyi/efi-backend-server#31]
Required pages:
- [x] Home
- [x] About pages
   - [x] EFIL
   - [x] EFIG
   - [x] CSR
   - [x] Newsroom
   - [x] Careers
      - [x] EFIL
      - [x] EFIG

Reference fields from [Design](https://figma.fun/KHeiJD) or [Static](https://efimm.netlify.app)
Use data from: [Client's copywriting](https://docs.google.com/document/d/16dLmh66SpsHH2N1zey2oA0vSwcApH1GZ/edit)

<hr />

Endpoint format: `/api/page/{ name }`

Request format:

```
{ locale: "en-US" }
```

Response format:
```
{
   block1_name: {
       field_name: string or number or url (multiple[] | single)
   },

   block2_name: {
       field_name: string or number or url (multiple[] | single)
   },

   ...
}
```

> you can name the `block_name` & `field_name` to anything u see fit. I'll re-map myself on frontend.

<hr />

Example for `Home` page:

endpoint: `/api/page/home`

payload: 
```
{ locale: "en-US" }
```

```
{
   slider: [
      {
        title: string,
        image: string,
        kind: 'two' // "one" or "three" or "four" or "five",
      },
      ...
   ],

   why_us: {
       image: 'https://example.com/triangle.jpg',
       title: string,
       description: string
   },

   claim_insurance: {
       title: string,
       description: string
       button_text: string
   },

   promotions: [
      {
        title: string,
        description: string
        image: string,
      },
      ...
   ],

   ...
}
```

**Comment by KonjiKonoha** [comment]
Please give the requested API format, bro.

**Comment by thihathit** [comment]
it's documented bro, here it is.

```{ locale: "en-US" }```
