### ISSUE TITLE
Job Position details API proposal

### ISSUE THREAD

**Issue by thihathit** [paingpyi/efi-backend-server#5]
endpoint: `/api/job/details`

`Request:`
```js
{
	"locale": "en-US",
	"sluge_url": ...
}
```

For this:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/30023628/164884434-142fd001-8923-4842-a988-cda0dace8aa1.png">

**Comment by KonjiKonoha** [comment]
Description is "Job Description".

**Comment by thihathit** [comment]
The design doesn't define sections, so i splitted into two.

```json
{
	"title:": "Financial consultant",
	"description": "<p>....</p>",
	"paragraphs": [
		{
			"title:": "Responsibility",
			"description": "<p>....</p>"
		},
		{
			"title:": "Things to know",
			"description": "<p>....</p>"
		},
		{
			"title:": "Benefits",
			"description": "<p>....</p>"
		}
	]
}
```

The first `title` is to serve as `h1`.
The first `description` is to serve as main description / job description.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/30023628/162596332-930c2087-782c-4dd7-b4dd-90af237b2c23.png">


Later `paragraphs` will be to serve additional info like, "Expected skillsets, Responsibility, Team ads, etc.."

<img width="269" alt="image" src="https://user-images.githubusercontent.com/30023628/162596327-02e882f3-40c0-49d6-83cd-927805548180.png">

**Comment by thihathit** [comment]
Another thing, if `/api/career` is the same as this proposal. It needs to support the request to be filterable using `slug_url`.
