### ISSUE TITLE
Job listing API

### ISSUE THREAD

**Issue by thihathit** [paingpyi/efi-backend-server#6]
for this
<img width="295" alt="image" src="https://user-images.githubusercontent.com/30023628/162557403-79eff840-1c5d-4624-ae97-ec52e2ae36e7.png">

**Comment by KonjiKonoha** [comment]
For List view, please use the following attribute.

{
"view": "list"
}

**Comment by thihathit** [comment]
> For List view, please use the following attribute.
> 
> { "view": "list" }

This works, I just found out another requirement.

We'll need to differentiate career `type`. The listing has two types, `Careers at EFI Life` & `Careers at EFI General`.

So basically, it's `life` or `general` again. so here's my expected request `payload`:

```
{
	"locale": "en-US",
	"view": "list",
	"type": "general" or "life"
}
```

**Comment by thihathit** [comment]
Next, `instant` checkbox in Backend. Which must be filterable in this list API. using payload

```js
{
   instant: true
}
```

For this

<img width="601" alt="image" src="https://user-images.githubusercontent.com/30023628/162602552-882de33a-3aa2-4979-9147-d37e48d9ef6e.png">

**Comment by thihathit** [comment]
We'll need to differentiate career `type`. The listing has two types, `Careers at EFI Life` & `Careers at EFI General`.

So basically, it's `life` or `general` again. so here's my expected request `payload`:

```js
{
	"locale": "en-US",
	"type": "general" or "life"
// OR
	"category_machine_name": "general" or "life"
}
```

**Comment by thihathit** [comment]
Needs to support `keywords` filter that targets to both `position` & `department` columns.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/30023628/164884344-3f26dee8-8248-45c2-abda-b9343958a389.png">

Like this:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/30023628/164884312-adb67ed7-9a14-4d5d-8d29-af9eea531c16.png">

**Comment by KonjiKonoha** [comment]
Bro you can use department for this.

**Comment by thihathit** [comment]
No. department isn't related to `type`.
